### ISSUE TITLE
CAD Dataset

### ISSUE THREAD

**Issue by SilenKZYoung** [kacperkan/ucsgnet#3]
HI, could you please re-provide the link to CAD Dataset, the original link seems to be invalid.
Thank you!

**Comment by kacperkan** [comment]
What do you mean by invalid? It doesn't load or something different? It loads for me without any issues
![image](https://user-images.githubusercontent.com/57393775/141035822-50dc7dfd-f289-4dec-99b5-c8b34b0ec3c6.png)

**Comment by SilenKZYoung** [comment]
Sorry, it seems that dropbox is not available in my area.
Can you provide a CAD dataset link to google drive, please!
thank you!

**Comment by kacperkan** [comment]
[here](https://drive.google.com/file/d/1hG4A8Ozlofz6mKz4F2MA_ZiRniAXLQR0/view?usp=sharing)

Note that I'm not the author of this dataset. If you're going to use, please acknowledge [the original authors](https://github.com/Hippogriff/CSGNet).

Therefore, I will delete this file from my drive in the next 24hrs so there's only one source of this dataset.

**Comment by SilenKZYoung** [comment]
Thank you very much!
