### ISSUE TITLE
ERROR: failed to reproduce 'dvc/3d_experiment/reconstruct_3d_shapes.dvc':

### ISSUE THREAD

**Issue by Komti13** [kacperkan/ucsgnet#5]
Hello everyone
When Trying the reconstruct_3d_shapes experiment, in the repro directory, the compilation fails at sample number 4811/8762 with the following error :
![166221900-43729049-059e-4cf2-85d5-264f37765090](https://user-images.githubusercontent.com/59767842/166909818-27aa067d-73ec-487f-802b-378725eb10a9.png)

raising the ZeroDivisionError line 58 of ucsgnet.mesh_utils.sample_point_polygon

if anyone can help!
Thanks

**Comment by Komti13** [comment]
I resolved it .. just run setup.py before to generate mesh_utils.c because i used another file mesh_utils which cause this error

**Comment by bigKoki** [comment]
I had the same problem when i run test with author's pretrained parameters，could you please describe how to solve it？
